name = "nlsc-wifi"
type = "webpack"
webpack_config = "./workers-site/webpack.config.js"

account_id = ""
workers_dev = true
routes = [ "wifi.skillsusanet.com/*" ]
#route = ""
zone_id = "ab3c5a844a558dbc8caed36fdc7a56ed"
compatibility_date = "2022-05-23"

site = { bucket = "./public" }
